Checking out commit 75371e7ca0b352a58285e17d5ad6106df09e2e38 in branch main
==> Common ways to troubleshoot your deploy: https://render.com/docs/troubleshooting-deploys
==> Build failed ðŸ˜ž
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Cannot import 'setuptools.build_meta'
    )
    ...<4 lines>...
    raise BackendUnavailable(
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 402, in _call_hook
    ^
    )
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        "get_requires_for_build_wheel", {"config_settings": config_settings}
           ~~~~~~~~~~~~~~~^
    return self._call_hook(
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 196, in get_requires_for_build_wheel
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
    return super().get_requires_for_build_wheel(config_settings=cs)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/utils/misc.py", line 702, in get_requires_for_build_wheel
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
    return backend.get_requires_for_build_wheel()
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/distributions/sdist.py", line 103, in _get_build_requires_wheel
    build_reqs = self._get_build_requires_wheel()
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/distributions/sdist.py", line 126, in _install_build_reqs
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
    self._install_build_reqs(finder)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/distributions/sdist.py", line 56, in prepare_distribution_metadata
    ^
    )
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        finder, build_isolation, check_build_deps
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
    abstract_dist.prepare_distribution_metadata(
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
    )
        self.check_build_deps,
    ...<3 lines>...
        req,
    dist = _get_prepared_distribution(
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/operations/prepare.py", line 647, in _prepare_linked_requirement
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/operations/prepare.py", line 532, in prepare_linked_requirement
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 317, in _prepare_distribution
    dist = self._prepare_distribution()
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 236, in _prepare
                ~~~~~~~~~~~~~^^
    self.dist = self._prepare()
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 159, in __init__
    ^
    )
        ^^^^^^^^^^^^^^^^
        version=version,
    ...<4 lines>...
        ^^^^^^^^^^
        link=link,
    ~~~~~~~~~~~~~~~~^
    super().__init__(
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 306, in __init__
    ^
    )
        ^^^^^^^^^^^^^^^^
        version=version,
    ...<3 lines>...
        ^^^^^
        link,
                                       ~~~~~~~~~~~~~^
    self._link_candidate_cache[link] = LinkCandidate(
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 233, in _make_base_candidate_from_link
    ^
    )
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        link, template, name, version
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 187, in _make_candidate_from_link
    candidate = func()
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 37, in _iter_built
                       ^^^^^^^^
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 147, in <genexpr>
                 ~~~^^^^^^
    self._bool = any(self)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 163, in __bool__
    return bool(self._sequence)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/structs.py", line 194, in __bool__
           ^^^^^^^^^^^^^^^^^^^^
    if not criterion.candidates:
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/resolvers/resolution.py", line 141, in _add_to_criteria
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    self._add_to_criteria(criteria, requirement, parent=candidate)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/resolvers/resolution.py", line 202, in _get_updated_criteria
    criteria = self._get_updated_criteria(candidate)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/resolvers/resolution.py", line 211, in _attempt_to_pin_criterion
    failure_criterion = self._attempt_to_pin_criterion(name)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/resolvers/resolution.py", line 444, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_vendor/resolvelib/resolvers/resolution.py", line 515, in resolve
    ^
    )
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        collected.requirements, max_rounds=limit_how_complex_resolution_can_be
                            ~~~~~~~~~~~~~~~~^
    result = self._result = resolver.resolve(
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 96, in resolve
    )
        reqs, check_supported_wheels=not options.target_dir
    requirement_set = resolver.resolve(
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/commands/install.py", line 387, in run
    return func(self, options, args)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/cli/req_command.py", line 68, in wrapper
           ~~~~~~~~^^^^^^^^^^^^^^^
    return self.run(options, args)
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    status = _inner_run()
  File "/opt/render/project/src/.venv/lib/python3.13/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
Traceback (most recent call last):
ERROR: Exception: